### ISSUE TITLE
Consider pros/cons of moving the Open Ownership map to higher resolution map images to make smaller islands visible

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/openownership.org-wagtail#143]
Smaller islands like [Mauritius](https://openownership.hactar.work/en/map/country/mauritius/) and other locations that Open Ownership works with are not visible on the Open Ownership Map as we are using a lower resolution GeoJSON file.

Need to consider the right balance here to see if it is more important to consider page speed or for users to be able to zoom in and click on these small islands.

**Comment by philgyford** [comment]
@StephenAbbott I can look into this again – just checking whether you've had any further thoughts on this since, or if there are any newer requirements I should bear in mind?

**Comment by philgyford** [comment]
I've done some work on the map now which means the smaller islands show up *and* the map file is much smaller.

- We use the "1:50m Cultural Vectors" "Admin 0 - Countries" map from https://www.naturalearthdata.com/downloads/50m-cultural-vectors/
- Using https://mapshaper.org we then simplify the outlines a bit and download it as TopoJSON (smaller than GeoJSON)
- There's a new script that processes that file, discards data we don't use, and fixes one other little issue
- The JavaScript now works with TopoJSON instead of GeoJSON.

So you can now zoom in click on Mauritius and Barbados (we could allow zooming in further if that helps?) and the size of the map file has been reduced from 577KB to 115KB.

**Comment by StephenAbbott** [comment]
Signed off ✅
