### ISSUE TITLE
500 error when trying to add new glossary item to Glossary page

### ISSUE THREAD

**Issue by StephenAbbott** [openownership/openownership.org-wagtail#331]
To edit the [Beneficial ownership glossary page on the Open Ownership website](https://www.openownership.org/en/implementation/beneficial-ownership-glossary/), users go to this [admin page](https://www.openownership.org/admin/pages/281/edit/) where they can edit glossary items and should be able to add new glossary items.

However we are currently unable to add new glossary items to this page. Attempting to do so and then saving the page to save changes generates a 500 error 
<img width="784" alt="image" src="https://user-images.githubusercontent.com/1506468/224334637-ab5662a0-8fdf-416b-a97a-fbb1d60b221e.png">

Could this please be investigated?

**Comment by drcongo** [comment]
@StephenAbbott I've been unable to reproduce this one, I've cloned the page from production so that I don't add glossary items to the live site and added glossary items with no trouble. I've also added one on staging without problems. My best guess is that the item you were attempting to add had NUL (0x00) characters in it which can happen when copying and pasting from a Word doc or similar - the only new issue in Bugsnag is an error caused by NUL characters in a translation (not glossary page though). Don't suppose you could send me what was being added?

**Comment by StephenAbbott** [comment]
@drcongo Unfortunately NUL characters is not what is causing this at our end.

If I go to https://www.openownership.org/admin/pages/281/edit, click the Insert a block button to 'Add glossary item', write in some text in the Title and Body field for the new Glossary item and then click Save, I get the 500 error.

**Comment by drcongo** [comment]
Fixed and (sort of) found the cause - I went into the history and compared revisions, and somehow wagtail was showing a newly saved revision but also saying it had no changes compared to a previous revision - so I rolled back to that previous revision and everything is back working. 

It's an odd error and we have seen it once or twice before, but we still don't know how it actually gets into that state in the first place.

**Comment by StephenAbbott** [comment]
Great if you can push this fix to live, @drcongo. Cheers!
